spring:
  datasource:
    url: jdbc:h2:file:/config/alist-tvbox/atv
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      data-locations: file:/config/alist-tvbox/atv/data.sql

logging:
  file:
    name: log/app.log
  level:
    cn.har01d: info
app:
  xiaoya: true
  sites:
    - name: 丫仙女
      url: http://localhost
      version: 3
      searchable: true
      xiaoya: true
