name: 'Release Docker'

on:
  workflow_run:
    workflows: ["Release Base"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github\workflows\build-hass.yaml
      - \hass\app_version

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: npm
          cache-dependency-path: ./web-ui

      - name: Install npm dependencies
        working-directory: ./web-ui
        run: npm ci

      - name: Build web UI
        working-directory: ./web-ui
        run: npm run build

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GH_TOKEN }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract Spring Boot layers
        working-directory: ./target
        run: java -Djarmode=layertools -jar alist-tvbox-1.0.jar extract

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry (ghcr)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set app version
        run: |
          echo "version=$(cat hass/app_version)" >> $GITHUB_ENV
        id: set_version

      - name: Build Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: hass/Dockerfile-xiaoya
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:latest,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:${{ env.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build host mode Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: hass/Dockerfile-host
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:hostmode,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:hostmode-${{ env.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build standalone Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: hass/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alist-tvbox:latest,ghcr.io/${{ github.repository_owner }}/alist-tvbox:${{ env.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build native with Maven
        run: |
          export TOOLCHAIN_DIR=/opt/x86_64-linux-musl-native/
          export CC=$TOOLCHAIN_DIR/bin/gcc
          export PATH="$TOOLCHAIN_DIR/bin:$PATH"
          sudo apt update
          sudo apt install build-essential libz-dev zlib1g-dev zlib1g -y
          wget https://more.musl.cc/10.2.1/x86_64-linux-musl/x86_64-linux-musl-native.tgz
          tar xf x86_64-linux-musl-native.tgz -C /opt
          wget https://zlib.net/zlib-1.3.1.tar.gz
          tar xf zlib-1.3.1.tar.gz
          cd zlib-1.3.1
          ./configure --prefix=$TOOLCHAIN_DIR --static
          make
          sudo make install
          cd ..
          mvn -B -Pnative package --file pom.xml

      - name: Build native Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: hass/Dockerfile-native
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-${{ env.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build host native Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: hass/Dockerfile-native-host
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-host,ghcr.io/${{ github.repository_owner }}/xiaoya-tvbox:native-host-${{ env.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
