name: 'Release Base'

on:
  workflow_run:
    workflows: ["Release Java"]
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract Spring Boot layers
        working-directory: ./target
        run: java -Djarmode=layertools -jar alist-tvbox-1.0.jar extract

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry (ghcr)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile-base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alist-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: TAG=latest

      - name: Build hostmode Docker and push to ghcr
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile-base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alist-base:hostmode
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: TAG=hostmode
